# Generated by Django 3.0.5 on 2020-10-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isima_trivez', '0002_pdfstore_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfstore',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
