# Generated by Django 3.1 on 2020-09-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isima_trivez', '0002_auto_20200927_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfstore',
            name='slug',
        ),
    ]
