# Generated by Django 3.1 on 2020-09-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isima_trivez', '0003_remove_pdfstore_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfstore',
            name='slug',
            field=models.SlugField(default='post_1'),
            preserve_default=False,
        ),
    ]
